[program:cron]
command=/usr/sbin/cron -f
process_name=%(program_name)s
numprocs=1
autostart=true
autorestart=true
redirect_stderr=true
startretries=30
startsecs=10
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s_error.log
