date.timezone = Asia/Shanghai
upload_max_filesize = 100M
post_max_size = 100M

[opcache]
opcache.enable = 1
opcache.enable_cli = 1
opcache.fast_shutdown = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 60
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 10000

[apcu]
apc.enabled = 1
apc.enable_cli = 1
apc.shm_size = 32M
apc.gc_ttl = 3600
apc.ttl = 0
